huma-look-and-feel-title = Look And Feel
huma-personalize-settings-page = Personalize Settings Page
huma-apply-theme = Choose and apply any of the palettes or apply the palette of the theme you installed in your browser
huma-advanced-view-mode-title = Advanced View Modes
huma-edit-sidebar-title = Edit Sidebar
huma-edit-webapps-title = Edit WebApps
huma-width-mode = Width mode

huma-vertical-tabs = Vertical tabs
huma-vertical-tabs-title = 
    .label = { huma-vertical-tabs }
huma-compact-mode = Compact Mode  (experimental)

huma-compact-mode-title =
    .label =  { huma-compact-mode }
huma-sidebar = Enabele Sidebar
huma-sidebar-title =
    .label =  { huma-sidebar }

pane-huma-title = Look N Feel

category-humabar =
    .tooltiptext = { pane-humabar-title }

pane-humabar-title = Edit Sidebar

category-more-from-huma =
    .tooltiptext = { pane-huma-title }

userChrome-theme-proton_color = Theme Proton Color
userChrome-theme-proton_color-title =
    .label = { userChrome-theme-proton_color }

 
userChrome-compatibility-os = Compatibility OS
userChrome-compatibility-os-title =
    .label = { userChrome-compatibility-os }
userChrome-compatibility-theme = Compatibility Theme
userChrome-compatibility-theme-title =
    .label = { userChrome-compatibility-theme }
userChrome-decoration-animate = Decoration Animate
userChrome-decoration-animate-title =
    .label = { userChrome-decoration-animate }
userChrome-decoration-cursor = Decoration Cursor
userChrome-decoration-cursor-title =
    .label = { userChrome-decoration-cursor }
userChrome-decoration-download_panel = Decoration Download Panel
userChrome-decoration-download_panel-title =
    .label = { userChrome-decoration-download_panel }
userChrome-decoration-field_border = Decoration Field Border
userChrome-decoration-field_border-title =
    .label = { userChrome-decoration-field_border }
userChrome-fullscreen-overlap = Fullscreen Overlap
userChrome-fullscreen-overlap-title =
    .label = { userChrome-fullscreen-overlap }
userChrome-fullscreen-show_bookmarkbar = Fullscreen Show Bookmark Bar
userChrome-fullscreen-show_bookmarkbar-title =
    .label = { userChrome-fullscreen-show_bookmarkbar }
userChrome-icon-1-25px_stroke = Icon 1-25px Stroke
userChrome-icon-1-25px_stroke-title =
    .label = { userChrome-icon-1-25px_stroke }
userChrome-icon-global_menu = Icon Global Menu
userChrome-icon-global_menu-title =
    .label = { userChrome-icon-global_menu }
userChrome-icon-global_menubar = Icon Global Menubar
userChrome-icon-global_menubar-title =
    .label = { userChrome-icon-global_menubar }
userChrome-icon-library = Icon Library
userChrome-icon-library-title =
    .label = { userChrome-icon-library }
userChrome-icon-menu = Icon Menu
userChrome-icon-menu-title =
    .label = { userChrome-icon-menu }
userChrome-icon-panel = Icon Panel
userChrome-icon-panel-title =
    .label = { userChrome-icon-panel }
userChrome-icon-panel_full = Icon Panel Full
userChrome-icon-panel_full-title =
    .label = { userChrome-icon-panel_full }
userChrome-icon-panel_photon = Icon Panel Photon
userChrome-icon-panel_photon-title =
    .label = { userChrome-icon-panel_photon }
userChrome-padding-bookmark_menu = Padding Bookmark Menu
userChrome-padding-bookmark_menu-title =
    .label = { userChrome-padding-bookmark_menu }
userChrome-padding-bookmarkbar = Padding Bookmark Bar
userChrome-padding-bookmarkbar-title =
    .label = { userChrome-padding-bookmarkbar }
userChrome-padding-global_menubar = Padding Global Menubar
userChrome-padding-global_menubar-title =
    .label = { userChrome-padding-global_menubar }
userChrome-padding-infobar = Padding Infobar
userChrome-padding-infobar-title =
    .label = { userChrome-padding-infobar }
userChrome-padding-menu = Padding Menu
userChrome-padding-menu-title =
    .label = { userChrome-padding-menu }
userChrome-padding-navbar_width = Padding Navbar Width
userChrome-padding-navbar_width-title =
    .label = { userChrome-padding-navbar_width }
userChrome-padding-panel = Padding Panel
userChrome-padding-panel-title =
    .label = { userChrome-padding-panel }
userChrome-padding-popup_panel = Padding Popup Panel
userChrome-padding-popup_panel-title =
    .label = { userChrome-padding-popup_panel }
userChrome-padding-tabbar_height = Padding Tabbar Height
userChrome-padding-tabbar_height-title =
    .label = { userChrome-padding-tabbar_height }
userChrome-padding-tabbar_width = Padding Tabbar Width
userChrome-padding-tabbar_width-title =
    .label = { userChrome-padding-tabbar_width }
userChrome-padding-toolbar_button = Padding Toolbar Button
userChrome-padding-toolbar_button-title =
    .label = { userChrome-padding-toolbar_button }
userChrome-padding-urlbar = Padding Urlbar
userChrome-padding-urlbar-title =
    .label = { userChrome-padding-urlbar }
userChrome-rounding-square_tab = Rounding Square Tab
userChrome-rounding-square_tab-title =
    .label = { userChrome-rounding-square_tab }
userChrome-tab-bar_separator = Tab Bar Separator
userChrome-tab-bar_separator-title =
    .label = { userChrome-tab-bar_separator }
userChrome-tab-bottom_rounded_corner = Tab Bottom Rounded Corner
userChrome-tab-bottom_rounded_corner-title =
    .label = { userChrome-tab-bottom_rounded_corner }
userChrome-tab-box_shadow = Tab Box Shadow
userChrome-tab-box_shadow-title =
    .label = { userChrome-tab-box_shadow }
userChrome-tab-close_button_at_hover = Tab Close Button at Hover
userChrome-tab-close_button_at_hover-title =
    .label = { userChrome-tab-close_button_at_hover }
userChrome-tab-color_like_toolbar = Tab Color Like Toolbar
userChrome-tab-color_like_toolbar-title =
    .label = { userChrome-tab-color_like_toolbar }
userChrome-tab-connect_to_window = Tab Connect to Window
userChrome-tab-connect_to_window-title =
    .label = { userChrome-tab-connect_to_window }
userChrome-tab-container = Tab Container
userChrome-tab-container-title =
    .label = { userChrome-tab-container }
userChrome-tab-crashed = Tab Crashed
userChrome-tab-crashed-title =
    .label = { userChrome-tab-crashed }
userChrome-tab-dynamic_separator = Tab Dynamic Separator
userChrome-tab-dynamic_separator-title =
    .label = { userChrome-tab-dynamic_separator }
userChrome-tab-lepton_like_padding = Tab Lepton Like Padding
userChrome-tab-lepton_like_padding-title =
    .label = { userChrome-tab-lepton_like_padding }
userChrome-tab-letters_cleary = Tab Letters Cleary
userChrome-tab-letters_cleary-title =
    .label = { userChrome-tab-letters_cleary }
userChrome-tab-multi_selected = Tab Multi Selected
userChrome-tab-multi_selected-title =
    .label = { userChrome-tab-multi_selected }
userChrome-tab-newtab_button_like_tab = Tab Newtab Button Like Tab
userChrome-tab-newtab_button_like_tab-title =
    .label = { userChrome-tab-newtab_button_like_tab }
userChrome-tab-newtab_button_proton = Tab Newtab Button Proton
userChrome-tab-newtab_button_proton-title =
    .label = { userChrome-tab-newtab_button_proton }
userChrome-tab-newtab_button_smaller = Tab Newtab Button Smaller
userChrome-tab-newtab_button_smaller-title =
    .label = { userChrome-tab-newtab_button_smaller }
userChrome-tab-photon_like_contextline = Tab Photon Like Contextline
userChrome-tab-photon_like_contextline-title =
    .label = { userChrome-tab-photon_like_contextline }
userChrome-tab-photon_like_padding = Tab Photon Like Padding
userChrome-tab-photon_like_padding-title =
    .label = { userChrome-tab-photon_like_padding }
userChrome-tab-pip = Tab Pip
userChrome-tab-pip-title =
    .label = { userChrome-tab-pip }
userChrome-tab-sound_hide_label = Tab Sound Hide Label
userChrome-tab-sound_hide_label-title =
    .label = { userChrome-tab-sound_hide_label }
userChrome-tab-sound_with_favicons = Tab Sound with Favicons
userChrome-tab-sound_with_favicons-title =
    .label = { userChrome-tab-sound_with_favicons }
userChrome-tab-static_separator = Tab Static Separator
userChrome-tab-static_separator-title =
    .label = { userChrome-tab-static_separator }
userChrome-tab-static_separator-selected_accent = Tab Static Separator Selected Accent
userChrome-tab-static_separator-selected_accent-title =
    .label = { userChrome-tab-static_separator-selected_accent }
userChrome-tab-unloaded = Tab Unloaded
userChrome-tab-unloaded-title =
    .label = { userChrome-tab-unloaded }
userChrome-theme-built_in_contrast = Theme Built-in Contrast
userChrome-theme-built_in_contrast-title =
    .label = { userChrome-theme-built_in_contrast }
userChrome-theme-fully_color = Theme Fully Color
userChrome-theme-fully_color-title =
    .label = { userChrome-theme-fully_color }
userChrome-theme-fully_dark = Theme Fully Dark
userChrome-theme-fully_dark-title =
    .label = { userChrome-theme-fully_dark }
userChrome-theme-proton_chrome = Theme Proton Chrome
userChrome-theme-proton_chrome-title =
    .label = { userChrome-theme-proton_chrome }


userChrome-icon-context_menu = Icon Context Menu
userChrome-icon-context_menu-title =
    .label = { userChrome-icon-context_menu }

userChrome-theme-system_default = System Default Theme
userChrome-theme-system_default-title =
    .label = { userChrome-theme-system_default }